kind: MLApp
workspace: test
metadata:
  name: tfexample
  labels: # Will be applayed to each resource
    testKey: testValue
spec:
  tasks:
  - name: model
    labels:
      testModelKey: testModelValue  # Will be applayed to each resource
    resources:
    - name: worker
      labels:
        testWorkerKey: testWorkerValue  # Will be applayed to each resource
      replicas: 2
      minAvailable: 2
      restartPolicy: Never
      maxRestartCount: 0
      waitCount: 2
      images:
        gpu: busybox
        cpu: busybox
      command:
      - 'echo'
      args: 'pythonpath=$PYTHONPATH;pwd=$(pwd)'
      workdir: "$SRC_DIR"
      env:
      - name: TEST_ENV_V1
        value: v1
      - name: PYTHONPATH
        value: /usr/local
      resources:
        accelerators:
          gpu: 1
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 100m
          memory: 1Gi
      port: 9000
      volumes:
      - name: lib
      - name: training
    - name: ps
      labels:
        testPsKey: testPsValue  # Will be applayed to each resource
      replicas: 1
      minAvailable: 1
      restartPolicy: Never
      maxRestartCount: 0
      waitCount: 0
      images:
        cpu: busybox
      command:
      - "/bin/sh -c  \"while true; do echo hi; sleep 10; done;\""
      workdir: "$SRC_DIR"
      port: 9000
      env:
      - name: TEST_ENV_V2
        value: v2
      volumes:
      - name: training
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/mlboard-jupyter-gpu:latest"
      cpu: "kuberlab/mlboard-jupyter:latest"
    resources:
      requests:
        cpu: 100m
        memory: 125Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    volumes:
    - name: lib
    - name: src
  - name: tensorboard
    displayName: Tensorboard
    images:
      cpu: "lsheiba/tensorflow-ls-devel"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    volumes:
    - name: training
  volumes:
  - name: lib
    isLibDir: true
    isTrainLogDir: false
    mountPath: /workspace/lib
    subPath: lib
    emptyDir: {}
  - name: training
    isLibDir: false
    isTrainLogDir: true
    mountPath: /workspace/training
    subPath: training
    emptyDir: {}
  - name: src
    isLibDir: false
    isTrainLogDir: false
    mountPath: /workspace/src
    subPath: src
    emptyDir: {}
